language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: cefdRy09R16Io/z6ViwtSDyq6wxJHJP55yM8fYqJIRYNSfanGk93A7vsEgv8QNsqsthkrundIzaAlq31Fw8iblum1igWjNmWAxG2pFLgJT+YoSw4JhWeaxsbkQEs4QCSpEJNvyOkgo/Nt7rXXApaCjWdyhaPWuMCn4yYD+GfG2sw48ZHf4TUndTq1Vq/1FUbbcgKmtNLgnGAPnEust7Rlb31nSFY4Q1adpb4yAddcbrUY4RYM3sDXwAZLZ8W3nvlrK+s8bj5LBG5ym+U2x2nBpkRLz9pzi1IjmWTxNnQNMi5ZT3VOMRR8RgIXjX2vsIEXMt8sD6eKcc+hu1C+JlWXVGh6RDyoHwfwZEwux0ykwWvdfH/zGJivRrVvrUmIbwY8HWNCuOJBnes0MpgrpUEXsJd0PpUMENinDPrGie+dAhNGC80NOp6iGj/u7xF3sOogMOLLgQBuH6hVoR6oL+syeK4irPeiK7qgRsm7L0G6QngOse91+TJG5n81qrR100w7GjdrxYE8yymzFedxMfl97wGMilAwnWEg7zqY4+NAHrd3KuK8032PM4idLSSNXuojYXMLld/H7+pkgmi4v/pLSsPyNz3rmRY4cu3X4VyDEsJVVBmkgeFoAg4mjI3QQeq+aCmOUocfI3x+QcIE2Yw78VtNScs0rbta2zf4NhsQOk=
  app: animetrics
  skip_cleanup: true
