language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: fv4WzDiepjycmQge0b6DrIrZytTD9ikPzvAV9pjfscpVaK54h7xxCKqbi3alY83XQIHJYNdyBb7eHiDnKcYob8iPUPqotsjvljc3pQQpLIhbzRZF+ergs7wwzfhkbFcnQJmHpTPOy9Vb1qZjWFs3qifzY9EvUTwtZkmFNYIcelIB9hwT0HErkxO4JI951apv7v3A7/ayPxWzZ3605ZfgZv+bj7iw6vHrMltP0n9Yb/9L5oW5YalqmOngTnCXrLXsKoMOsUvdXAS6/0fZCxVm7QrXJbBrY5kKJpoxtAuOPTkUd4AMGOk8r+4Sf8d+QkrVklGf5MeN1GtnbPVnNvDzzdQxomfQoAeFmEEJbrH+J4cxwRpIRNSszfx4ThOgUCV99K4HTjM/z1Gny792eDucDHBvP0GvRk40twJFCd+zqqzZwaHwluJnGw7WDmHWBc7G3IJ9M17VYq+fV1y4ShdUXoyz1JohTohfxp1ZqGJzo/VseXfbqvsOSUSKc4fdvD/ILAiLwmGFOtIviEhas8cdMvueB37tJ3914KtaPUrSGdzTJXOjb6MHUaypQoEFLMTMzY4jnP7wr666ZIgj3b7ouXomoMR9CrWYgZORszZvY5vPXttnRj6aPiICQ4c3XIOjdg10QfMHbZ5JxIV5mZS70l5NafDEqEzBDgZNYUM+9ms=
  app: animetrics
  skip_cleanup: true
